# Dependencies
markdown:         kramdown
highlighter:      rouge
gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Andy Fiedler'
tagline:          ''
description:      ''
url:              http://andyfiedler.com
baseurl:          /

author:
  name:           'Andy Fiedler'
  url:            https://twitter.com/andyfiedler

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
