source 'https://rubygems.org'


gem 'jekyll'
gem 'jekyll-import'
gem 'jemoji'
gem 'jekyll-paginate'
gem 'jekyll-picture-tag'
gem 'jekyll-redirect-from'
gem 'jekyll-sass-converter'
gem 'jekyll-watch'
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'jekyll-gist'
gem 'rouge'
